---
- name: Run privileged tasks
  import_tasks: "{{ role_path }}/tasks/priv.yml"
  when: privileged
  become: true

- name: Run unprivileged tasks
  import_tasks: "{{ role_path }}/tasks/unpriv.yml"
  when: not privileged