---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_pkg_mgr == "apt"
  tags:
    - install

- name: Update yum cache
  ansible.builtin.yum:
    update_cache: yes
  when: ansible_pkg_mgr == "yum"
  tags:
    - install

- name: Update apk cache
  community.general.apk:
    update_cache: yes
  when: ansible_pkg_mgr == "apk"
  tags:
    - install

- name: Update dnf cache
  ansible.builtin.dnf:
    update_cache: yes
  when: ansible_pkg_mgr == "dnf"
  tags:
    - install

- name: Update zypper cache
  community.general.zypper:
    name: zypper
    update_cache: yes
  when: ansible_pkg_mgr == "zypper"
  tags:
    - install

- name: Update pacman cache
  community.general.pacman:
    update_cache: yes
  when: ansible_pkg_mgr == "pacman"
  tags:
    - install

- name: "Install rsync and {{ shell }}"
  package:
    name:
      - rsync
      - "{{ shell }}"
    state: present
  tags:
    - install

- name: "Check if {{ shell }} exists in PATH"
  command: "which {{ shell }}"
  register: shell_path
  changed_when: false
  tags:
    - configure

- name: Set shell
  user:
    name: "{{ shelluser }}"
    shell: "{{ shell_path }}"
  tags:
    - configure

- name: Disable password login over SSH
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} {{item.value}}"
    state: present
  loop:
    - { key: "PermitRootLogin", value: "{{ rootlogin }}" }
    - { key: "PasswordAuthentication", value: "{{ pwauth }}" }
  notify:
    - restart sshd
  tags:
    - configure

- name: Run unprivileged tasks
  import_tasks: "{{ role_path }}/tasks/unpriv.yml"
  become: true
  become_user: "{{ shelluser }}"