---
- name: Add SSH key
  authorized_key:
    user: "{{ shelluser }}"
    state: present
    key: "{{ ssh_key }}"
  tags:
    - configure

- name: Get user info
  user:
    name: "{{ shelluser }}"
    state: present
  register: shelluser_info

- name: Copy user config with rsync
  synchronize:
    src: "{{ dotfiles }}"
    dest: "{{ shelluser_info.home }}"
    archive: false
    recursive: true
  register: rsync_status
  ignore_errors: true
  tags:
    - configure
    - file

- name: Copy user config with builtin copy module
  copy:
    src: "{{ dotfiles }}"
    dest: "{{ shelluser_info.home }}"
  when: rsync_status.rc != 0
  tags:
    - configure
    - file

- name: Set user shell (unprivileged)
  block:
    - name: "Check if {{ shell }} exists in PATH"
      command: "which {{ shell }}"
      register: shell_path
      changed_when: false

    - name: Get user shell
      user:
        name: "{{ shelluser }}"
        shell: "{{ shell_path.stdout }}"
      register: setshell
      check_mode: true

    - pause:
        prompt: "Password for {{ ansible_user_id }}@{{ ansible_host }}"
        echo: false
      when: setshell.changed
      register: password_prompt
      no_log: true

    - name: Run chsh to change shell
      command: "chsh -s {{ shell_path.stdout }}"
      args:
        stdin: "{{ password_prompt.user_input }}"
      when: setshell.changed
  when: not privileged
  tags:
   - configure